### ISSUE TITLE
Crashes the app as soon as added

### ISSUE THREAD

**Issue by serkandurusoy** [East5th/check-checker#10]
as soon as I `meteor add east5h:check-checker` and `meteor run` I get the following output

``` bash
=> Started proxy.                             

/home/devmachine/.meteor/packages/static-html/.1.0.7.1evw59a++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: No os unibuild for null!
    at Error (<anonymous>)
    at lintUnibuild (/tools/isobuild/compiler.js:304:11)
    at /tools/isobuild/compiler.js:218:30
    at Array.forEach (native)
    at Function._.each._.forEach (/home/devmachine/.meteor/packages/meteor-tool/.1.3.2_4.jf6chy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.lint (/tools/isobuild/compiler.js:211:5)
    at lintBundle (/tools/isobuild/bundler.js:2662:54)
    at /tools/isobuild/bundler.js:2537:25
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

The only remedy so far seems to be just removing the package which returns everything to normal.

This is an ES2015 `METEOR@1.3.2.4` project with everything within the `imports` folder if that matters.

**Comment by pcorey** [comment]
Hey, good catch! It looks like this is a [known issue](https://github.com/meteor/meteor/issues/6843) with Meteor. It also looks like they've got a fix for it in the `1.3.3-beta.0` release.

Does upgrading to that beta release fix your problem?

```
meteor update --release 1.3.3-beta.0
```

**Comment by serkandurusoy** [comment]
Oh, that's great. Although I am not able to test betas right now (in
lightspeed development mode) I'm going to do that first thing after the
release upgrade.

Thank you!

**Comment by serkandurusoy** [comment]
I do confirm that 1.3 solves this issue.

**Comment by pcorey** [comment]
:+1:
