### ISSUE TITLE
ESLint issue on Windows

### ISSUE THREAD

**Issue by DevanB** [East5th/check-checker#3]
I'm seeing an issue on Windows when I load up an app that is using check-checker. Any help? Below is the stack trace.

```
W20150911-10:28:10.497(-5)? (STDERR) Error: ENOENT, no such file or directory 'C:\projects\c4q\.meteor\local\build\programs\server\undefined'

W20150911-10:28:10.497(-5)? (STDERR)     at Object.fs.statSync (fs.js:696:18)

W20150911-10:28:10.497(-5)? (STDERR)     at walk (C:\Users\ctpayne\AppData\Local\.meteor\packages\east5th_eslint\0.0.2\npm\node_modules\eslint\lib\util\traverse.js:36:15)

W20150911-10:28:10.498(-5)? (STDERR)     at C:\Users\ctpayne\AppData\Local\.meteor\packages\east5th_eslint\0.0.2\npm\node_modules\eslint\lib\util\traverse.js:102:9

W20150911-10:28:10.498(-5)? (STDERR)     at Array.forEach (native)

W20150911-10:28:10.498(-5)? (STDERR)     at traverse (C:\Users\ctpayne\AppData\Local\.meteor\packages\east5th_eslint\0.0.2\npm\node_modules\eslint\lib\util\traverse.js:101:11)

W20150911-10:28:10.498(-5)? (STDERR)     at CLIEngine.executeOnFiles (C:\Users\ctpayne\AppData\Local\.meteor\packages\east5th_eslint\0.0.2\npm\node_modules\eslint\lib\cli-engine.js:313:9)

W20150911-10:28:10.498(-5)? (STDERR)     at Package (packages/east5th:check-checker/lib/check-checker.js:21:1)

W20150911-10:28:10.498(-5)? (STDERR)     at C:\projects\c4q\.meteor\local\build\programs\server\boot.js:229:5
```

**Comment by DevanB** [comment]
Running Windows 7, 64-bit.

**Comment by pcorey** [comment]
Just pushed a fix. Try updating to 0.0.5.
