### ISSUE TITLE
Fatal error after adding east5th:check-checker

### ISSUE THREAD

**Issue by mquandalle** [East5th/check-checker#6]
Hi,

I get the following error after adding `east5th:check-checker` to my application:

```
Error: Cannot find module 'eslint-config-eslint:recommended'
Referenced from: /home/maxime/meteor/wekan/.eslintrc
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadConfig (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/config.js:96:48)
    at /home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/config.js:111:36)
    at getLocalConfig (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/config.js:363:22)
    at processText (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/cli-engine.js:226:12)
    at /home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/cli-engine.js:322:26
    at /home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at traverse (/home/maxime/.meteor/packages/east5th_eslint/.0.0.2.aod45j++os+web.browser+web.cordova/npm/node_modules/eslint/lib/util/traverse.js:41:54)
```

Is this a missing dependency?

**Comment by pcorey** [comment]
It looks like this package isn't behaving nicely when an [`.eslintrc`](https://github.com/wekan/wekan/blob/devel/.eslintrc) is present in your project. I'll look for a fix.

**Comment by pcorey** [comment]
@mquandalle This should be fixed now. Try updating to 0.0.8. Sorry for the delay!

**Comment by pcorey** [comment]
Thought I just tried it out on Wekan, and it probably still won't work. I'm still working on supporting ES6 syntax.
